# Generated by Django 5.0.6 on 2025-11-03 20:48

import siteapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=siteapp.models.upload_to
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=64)),
                ("symptoms", models.JSONField(default=list)),
                ("results", models.JSONField(default=dict)),
                ("quality_info", models.JSONField(default=dict)),
            ],
        ),
    ]
